### ISSUE TITLE
Missing Setups

### ISSUE THREAD

**Issue by Eslam3bed** [mohanagy/node-typescript-express-boilerplate#1]
### Todo list of must to have configurations:
- [ ] Using passport for authentication schemes
- [ ] Support `dotenv `for reading and injecting vars
- [ ] DB's connection support (starting with NoSQL MongoDB)
- [ ] Workflow for publishing tagging, versioning, and publishing to npm with Github actions.

**Comment by Eslam3bed** [comment]
@mohanagy add label `discussion` to this issue
so we can iterate and convert the things we should have into tasks to be worked on
